import { useEffect, useState } from 'react';
import { Alert, Autocomplete, Box, Button, Grid, Paper, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import MainCard from 'ui-component/cards/MainCard';
import api from '@/api/axios.js';

const money = (value) => `Rp ${new Intl.NumberFormat('id-ID').format(value || 0)}`;
const today = new Date().toISOString().slice(0, 10);

export default function CashDailyPage() {
  const [date, setDate] = useState(today); const [data, setData] = useState(null); const [error, setError] = useState('');
  const [opening, setOpening] = useState(''); const [closing, setClosing] = useState('');
  const [withdrawal, setWithdrawal] = useState({ user_id: '', amount: '', service_fee: '', description: '' });
  const [members, setMembers] = useState([]);
  const load = async () => { try { const response = await api.get('/cash-daily', { params: { date } }); setData(response.data.data); setOpening(response.data.data.session.actual_opening_balance ?? ''); setClosing(response.data.data.session.actual_closing_balance ?? ''); } catch (e) { setError(e.response?.data?.message || 'Kas harian gagal dimuat.'); } };
  useEffect(() => { load(); }, [date]);
  useEffect(() => { api.get('/cash-daily/members').then((response) => setMembers(response.data?.data || [])).catch(() => setMembers([])); }, []);
  const saveSession = async (fields) => { await api.patch(`/cash-daily/${data.session.id}`, fields); await load(); };
  const saveWithdrawal = async () => { try { await api.post(`/cash-daily/${data.session.id}/withdrawals`, withdrawal); setWithdrawal({ user_id: '', amount: '', service_fee: '', description: '' }); await load(); } catch (e) { setError(e.response?.data?.message || 'Penarikan gagal dicatat.'); } };
  const expected = data?.expected_balance || 0;
  return <MainCard title="Kas Harian">
    <Grid container spacing={2} sx={{ mb: 2 }}><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth type="date" label="Tanggal Kas" value={date} onChange={(e) => setDate(e.target.value)} slotProps={{ inputLabel: { shrink: true } }} /></Grid><Grid size={{ xs: 12, sm: 9 }}><Typography color="text.secondary">Saldo awal otomatis diambil dari penutupan kas sebelumnya. Penjualan dengan metode Cash/Tunai masuk otomatis ke rekap.</Typography></Grid></Grid>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    {data && <><Grid container spacing={2} sx={{ mb: 3 }}>{[['Saldo Awal Sistem', data.session.opening_balance], ['Penjualan Tunai', data.cash_sales], ['Saldo Seharusnya', expected], ['Saldo Akhir Opname', data.session.actual_closing_balance]].map(([label, value]) => <Grid key={label} size={{ xs: 6, md: 3 }}><Paper variant="outlined" sx={{ p: 2 }}><Typography variant="caption">{label}</Typography><Typography variant="h5">{money(value)}</Typography></Paper></Grid>)}</Grid>
      <Grid container spacing={2} sx={{ mb: 3 }}><Grid size={{ xs: 12, md: 6 }}><Paper variant="outlined" sx={{ p: 2 }}><Typography variant="h6">Cash Opname Pagi</Typography><TextField fullWidth type="number" label="Uang fisik saat buka" value={opening} onChange={(e) => setOpening(e.target.value)} sx={{ my: 1 }} /><Button variant="outlined" onClick={() => saveSession({ actual_opening_balance: opening })}>Simpan Opname Pagi</Button></Paper></Grid><Grid size={{ xs: 12, md: 6 }}><Paper variant="outlined" sx={{ p: 2 }}><Typography variant="h6">Penutupan Kas</Typography><TextField fullWidth type="number" label="Uang fisik saat tutup" value={closing} onChange={(e) => setClosing(e.target.value)} sx={{ my: 1 }} /><Button variant="contained" onClick={() => saveSession({ actual_closing_balance: closing })}>Simpan Saldo Akhir</Button></Paper></Grid></Grid>
      <Paper variant="outlined" sx={{ p: 2, mb: 3 }}><Typography variant="h6">Penarikan Uang Anggota</Typography><Grid container spacing={1} sx={{ mt: 1 }}><Grid size={{ xs: 12, sm: 3 }}><Autocomplete options={members} getOptionLabel={(member) => `${member.name}${member.username ? ` (${member.username})` : ''}`} onChange={(_, member) => setWithdrawal({ ...withdrawal, user_id: member?.id || '' })} renderInput={(params) => <TextField {...params} label="Pilih Anggota" />} /></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth required type="number" label="Nominal Penarikan" value={withdrawal.amount} onChange={(e) => setWithdrawal({ ...withdrawal, amount: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 2 }}><TextField fullWidth required type="number" label="Jasa" value={withdrawal.service_fee} onChange={(e) => setWithdrawal({ ...withdrawal, service_fee: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 2 }}><TextField fullWidth label="Keterangan" value={withdrawal.description} onChange={(e) => setWithdrawal({ ...withdrawal, description: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 2 }}><Button fullWidth variant="contained" disabled={!withdrawal.amount || !withdrawal.user_id} onClick={saveWithdrawal}>Catat</Button></Grid></Grid></Paper>
      <Typography variant="h6">Mutasi Manual Hari Ini</Typography><Table size="small"><TableHead><TableRow><TableCell>Jenis</TableCell><TableCell>Keterangan</TableCell><TableCell align="right">Kas Masuk</TableCell><TableCell align="right">Kas Keluar</TableCell></TableRow></TableHead><TableBody>{data.entries.length ? data.entries.map((entry) => <TableRow key={entry.id}><TableCell>{entry.type === 'withdrawal' ? 'Penarikan Anggota' : 'Jasa Penarikan'}</TableCell><TableCell>{entry.description}</TableCell><TableCell align="right">{money(entry.cash_in)}</TableCell><TableCell align="right">{money(entry.cash_out)}</TableCell></TableRow>) : <TableRow><TableCell colSpan={4} align="center">Belum ada mutasi manual.</TableCell></TableRow>}</TableBody></Table></>}
  </MainCard>;
}
